highlighter: pygments
safe: true
lsi: false

# Site settings
title: Kaltura VPaaS Usage Dashboard
baseurl: "/kaltura-html" 
url: "http://pulsevt.github.io"

github_username:  PulseVT
email: vitaliy.tarash@gmail.com